### ISSUE TITLE
Question: Many cell in same Row it's possible?

### ISSUE THREAD

**Issue by rodrigosmarques** [Realank/flutter_section_table_view#2]
Congratulations on your package. I needed a package with this one to rewrite a native app.

In one of my app I need to have several Widgets per line in each session, like the IOS UICollection. 

See the image below. I can do this with your package. Do you have any suggestions?

![image](https://user-images.githubusercontent.com/17687286/50553553-15148100-0c90-11e9-986f-661f3364b16f.png)

**Comment by Realank** [comment]
thanks for your use, how about embed gridView into cells?

**Comment by rodrigosmarques** [comment]
I did not get to try a gridview, because the cellAtIndexPath is called for each cell.
In my app the sections and lines are very variable and when the user clicks on the cell I need to identify the section and the line that was clicked and your package gives me this return, just like I do today on iOS and native Android.
I'm starting on Flutter now.
I'm going to study your package and see how I can put a Widget in front of the other until I fill the line.

Thank you.

**Comment by Realank** [comment]
oh, I see. I think you may not use this package, just use list view embed with grideView is better, in each grideView item, wrap a Flatbutton or InkWell out of your real circle item

**Comment by rodrigosmarques** [comment]
Thanks for the sugestion. It took me a while, but I managed to do it. I used a Listview, a StickyHeader (sticky_headers: ^ 0.1.7) and in the content, I put a Gridview.

I have to build logic to search and find an item in the structure.

Thank you again.

![image](https://user-images.githubusercontent.com/17687286/50622917-2c55a780-0ef8-11e9-9bda-cf5b43ef6c33.png)

**Comment by Realank** [comment]
you are welcome, and congratulations you find out the solution
