### ISSUE TITLE
是否可以放开ListView.builder的padding属性

### ISSUE THREAD

**Issue by pcccccc** [Realank/flutter_section_table_view#7]
最近在做项目时遇到了一个问题：
在不使用AppBar时展示listView需要将padding: EdgeInsets.only(top: 0) 顶部才不会有空白. 

<img width="437" alt="图片" src="https://user-images.githubusercontent.com/13974510/55934795-5b508780-5c64-11e9-87d7-7f20e920b2ab.png">

**Comment by Realank** [comment]
如果你没有加safearea，那么上面的padding是ListView自己加的，当向上滚动的时候，padding里也会显示list的内容，我们最好还是维持ListView自己的特性，如果你不想要这个padding，那么请用你说的这个方法来规避。
不过话说回来，你的app不需要躲避刘海部分吗

**Comment by pcccccc** [comment]
请问使用flutter_section_table_view时应该如何修改SectionTableView的padding，因为一个特殊的需求我需要隐藏appbar。

**Comment by Realank** [comment]
在SectionTableView外直接包住一个Padding如果不管用的话，建议fork一套代码到自己的名下，然后修改内部代码

**Comment by pcccccc** [comment]
> 在SectionTableView外直接包住一个Padding如果不管用的话，建议fork一套代码到自己的名下，然后修改内部代码

问题已经解决，感谢。
